sets.exported={
    main="Arasy Sainti",
    ammo="Honed Tathlum",
    head="Ken. Jinpachi",
    body="Ken. Samue",
    hands="Ken. Tekko",
    legs="Ken. Hakama",
    feet="Ken. Sune-Ate",
    neck="Iqabi Necklace",
    waist="Cetl Belt",
    left_ear="Steelflash Earring",
    right_ear="Bladeborn Earring",
    left_ring="Rajas Ring",
    right_ring="Enlivened Ring",
    back={ name="Segomo's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','DEX+5','"Dbl.Atk."+10',}},
}