sets.exported={
    main="Sandung",
    sub="Eminent Dagger",
    range="Moonring Blade",
    head="Espial Cap",
    body="Espial Gambison",
    hands={ name="Plun. Armlets +1", augments={'Enhances "Perfect Dodge" effect',}},
    legs="Espial Hose",
    feet="Jute Boots +1",
    neck="Spectacles",
    waist="Cetl Belt",
    left_ear="Allegro Earring",
    right_ear="Thunder Earring",
    left_ring="Enlivened Ring",
    right_ring="Rajas Ring",
    back="Aife's Mantle",
}