sets.exported={
    main="Marin Staff",
    sub="Enki Strap",
    ammo="Elis Tome",
    head="C. Palug Crown",
    body="Inyanga Jubbah +1",
    hands="Inyanga Dastanas",
    legs={ name="Chironic Hose", augments={'Blood Pact Dmg.+6','Pet: STR+9','Accuracy+11 Attack+11','Mag. Acc.+15 "Mag.Atk.Bns."+15',}},
    feet="Skaoi Boots",
    neck="Noetic Torque",
    waist="Rumination Sash",
    left_ear="Lifestorm Earring",
    right_ear="Psystorm Earring",
    left_ring="Mediator's Ring",
    right_ring="Ayanmo Ring",
    back="Refraction Cape",
}