sets.exported={
    main="Malignance Pole",
    sub="Enki Strap",
    ammo="Staunch Tathlum",
    head="Inyanga Tiara +1",
    body="Inyanga Jubbah +1",
    hands="Inyan. Dastanas +1",
    legs="Inyanga Shalwar +1",
    feet="Inyan. Crackows +1",
    neck="Loricate Torque +1",
    waist="Fucho-no-Obi",
    left_ear="Odnowa Earring +1",
    right_ear="Novia Earring",
    left_ring="Defending Ring",
    right_ring="Shneddick Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','MND+5','Enmity-10','Damage taken-5%',}},
}