sets.exported={
    main="Kaja Sword",
    sub="Machaera",
    ammo="Jukukik Feather",
    head={ name="Herculean Helm", augments={'Accuracy+8 Attack+8','Weapon skill damage +5%','Accuracy+3',}},
    body="Assim. Jubbah +2",
    hands="Jhakri Cuffs +2",
    legs="Aya. Cosciales +1",
    feet="Aya. Gambieras +1",
    neck="Tjukurrpa Medal",
    waist="Prosilio Belt",
    left_ear="Brutal Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Rajas Ring",
    right_ring="Ifrit Ring",
    back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}