sets.exported={
    main="Ababinili",
    sub="Fulcio Grip",
    ammo="Clarus Stone",
    head="Befouled Crown",
    body={ name="Telchine Chas.", augments={'"Cure" potency +7%',}},
    hands="Dynasty Mitts",
    legs={ name="Piety Pantaloons", augments={'Enhances "Afflatus Misery" effect',}},
    feet="Orsn. Duckbills +2",
    neck="Colossus's Torque",
    waist="Olympus Sash",
    left_ear="Lifestorm Earring",
    right_ear="Novia Earring",
    left_ring="Mediator's Ring",
    right_ring="Ephedra Ring",
    back="Mending Cape",
}