sets.exported={
    main="Kaja Sword",
    sub="Tanmogayi +1",
    ammo="Jukukik Feather",
    head={ name="Taeon Chapeau", augments={'Attack+11','Crit.hit rate+3','Crit. hit damage +3%',}},
    body={ name="Qaaxo Harness", augments={'Attack+15','Evasion+15','"Dbl.Atk."+2',}},
    hands={ name="Taeon Gloves", augments={'Accuracy+12','"Triple Atk."+2',}},
    legs={ name="Taeon Tights", augments={'Accuracy+11','"Triple Atk."+2',}},
    feet={ name="Taeon Boots", augments={'Accuracy+12','"Triple Atk."+2',}},
    neck="Asperity Necklace",
    waist="Chaac Belt",
    left_ear="Brutal Earring",
    right_ear="Suppanomimi",
    left_ring="Mars's Ring",
    right_ring="Rajas Ring",
    back="Atheling Mantle",
}