sets.exported={
    main="Earth Staff",
    sub="Irenic Strap",
    ammo="Staunch Tathlum",
    head="Theophany Cap",
    body="Count's Garb",
    hands={ name="Telchine Gloves", augments={'"Cure" potency +7%',}},
    legs="Aya. Cosciales +1",
    feet={ name="Helios Boots", augments={'"Mag.Atk.Bns."+24','Magic crit. hit rate +6','MP+9',}},
    neck="Twilight Torque",
    waist="Witful Belt",
    left_ear="Loquac. Earring",
    right_ear="Gwati Earring",
    left_ring="Persis Ring",
    right_ring="Rajas Ring",
    back={ name="Alaunus's Cape", augments={'Damage taken-5%',}},
}