sets.exported={
    main="Daybreak",
    sub="Ammurapi Shield",
    ammo="Elis Tome",
    head="C. Palug Crown",
    body="Inyanga Jubbah +2",
    hands="Inyan. Dastanas +2",
    legs="Aya. Cosciales +1",
    feet="Skaoi Boots",
    neck="Noetic Torque",
    waist="Rumination Sash",
    left_ear="Malignance Earring",
    right_ear="Gwati Earring",
    left_ring="Sangoma Ring",
    right_ring="Ayanmo Ring",
    back="Refraction Cape",
}