sets.exported={
    main="Malignance Pole",
    sub="Alber Strap",
    ammo="Staunch Tathlum",
    head="Befouled Crown",
    body="Acad. Gown +1",
    hands={ name="Hagondes Cuffs", augments={'Phys. dmg. taken -2%','"Mag.Atk.Bns."+10',}},
    legs="Assid. Pants +1",
    feet={ name="Helios Boots", augments={'"Mag.Atk.Bns."+24','Magic crit. hit rate +6','MP+9',}},
    neck="Loricate Torque +1",
    waist="Fucho-no-Obi",
    left_ear="Odnowa Earring +1",
    right_ear="Savant's Earring",
    left_ring="Shneddick Ring",
    right_ring="Defending Ring",
    back="Umbra Cape",
}