sets.exported={
    main="Daybreak",
    sub="Ammurapi Shield",
    ammo="Elis Tome",
    head="C. Palug Crown",
    body="Ayanmo Corazza +2",
    hands="Aya. Manopolas +1",
    legs={ name="Chironic Hose", augments={'Blood Pact Dmg.+6','Pet: STR+9','Accuracy+11 Attack+11','Mag. Acc.+15 "Mag.Atk.Bns."+15',}},
    feet="Orvail Souliers +1",
    neck="Eddy Necklace",
    waist="Fucho-no-Obi",
    left_ear="Malignance Earring",
    right_ear="Gwati Earring",
    left_ring="Mediator's Ring",
    right_ring="Archon Ring",
    back="Toro Cape",
}