sets.exported={
    main="Tanmogayi +1",
    sub={ name="Claidheamh Soluis", augments={'Accuracy+6','"Dbl.Atk."+2','DMG:+9',}},
    ammo="Jukukik Feather",
    head={ name="Herculean Helm", augments={'Crit.hit rate+2','CHR+6','Accuracy+20 Attack+20',}},
    body="Ayanmo Corazza +2",
    hands={ name="Taeon Gloves", augments={'Attack+14','Crit.hit rate+3','Crit. hit damage +1%',}},
    legs={ name="Taeon Tights", augments={'Accuracy+9','Crit.hit rate+3','STR+1 VIT+1',}},
    feet="Aya. Gambieras +1",
    neck="Light Gorget",
    waist="Snow Belt",
    left_ear="Steelflash Earring",
    right_ear="Bladeborn Earring",
    left_ring="Rajas Ring",
    right_ring="Ramuh Ring",
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+5','Crit.hit rate+10','Damage taken-5%',}},
}