sets.exported={
    main="Ababinili",
    sub="Irenic Strap",
    ammo="Incantor Stone",
    head="Nahtirah Hat",
    body="Inyanga Jubbah +1",
    hands={ name="Gendewitha Gages", augments={'Phys. dmg. taken -1%','Song recast delay -1',}},
    legs="Artsieq Hose",
    feet="Chelona Boots",
    neck="Aceso's Choker",
    waist="Witful Belt",
    left_ear="Loquac. Earring",
    right_ear="Gwati Earring",
    left_ring="Persis Ring",
    right_ring="Rajas Ring",
    back="Swith Cape",
}