sets.exported={
    main="Tizona",
    sub={ name="Machaera +2", augments={'TP Bonus +1000',}},
    ammo="Jukukik Feather",
    head={ name="Herculean Helm", augments={'Accuracy+8 Attack+8','Weapon skill damage +5%','Accuracy+3',}},
    body="Assim. Jubbah +3",
    hands="Jhakri Cuffs +2",
    legs={ name="Taeon Tights", augments={'Accuracy+9','Crit.hit rate+3','Weapon skill damage +3%',}},
    feet={ name="Herculean Boots", augments={'Attack+27','Weapon skill damage +4%','STR+7',}},
    neck="Tjukurrpa Medal",
    waist={ name="Sailfi Belt +1", augments={'Path: A',}},
    left_ear="Brutal Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Rajas Ring",
    right_ring="Ifrit Ring",
    back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}