sets.exported={
    main="Yagrush",
    sub="Sors Shield",
    ammo="Clarus Stone",
    head="Nahtirah Hat",
    body="Ebers Bliaud +1",
    hands={ name="Fanatic Gloves", augments={'MP+50','Healing magic skill +10','"Conserve MP"+7','"Fast Cast"+7',}},
    legs="Theo. Pantaloons",
    feet="Gende. Galoshes",
    neck="Malison Medallion",
    waist="Cetl Belt",
    left_ear="Lifestorm Earring",
    right_ear="Novia Earring",
    left_ring="Mediator's Ring",
    right_ring="Ephedra Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','MND+5','Enmity-10','Damage taken-5%',}},
}