sets.exported={
    main="Homestead Dagger",
    sub="Eminent Dagger",
    ammo="Jukukik Feather",
    head={ name="Herculean Helm", augments={'Accuracy+8 Attack+8','Weapon skill damage +5%','Accuracy+3',}},
    body={ name="Qaaxo Harness", augments={'Attack+15','Evasion+15','"Dbl.Atk."+2',}},
    hands={ name="Taeon Gloves", augments={'Accuracy+12','"Triple Atk."+2',}},
    legs="Limbo Trousers",
    feet={ name="Taeon Boots", augments={'Accuracy+12','"Triple Atk."+2',}},
    neck="Asperity Necklace",
    waist="Eschan Stone",
    left_ear="Friomisi Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Shiva Ring",
    right_ring="Shiva Ring",
    back="Atheling Mantle",
}