sets.exported={
    main="Kaja Sword",
    sub={ name="Machaera +2", augments={'TP Bonus +1000',}},
    ammo="Honed Tathlum",
    head="Jhakri Coronal",
    body="Assim. Jubbah +2",
    hands="Jhakri Cuffs +2",
    legs="Jhakri Slops +1",
    feet={ name="Taeon Boots", augments={'Accuracy+12','"Triple Atk."+2',}},
    neck="Soil Gorget",
    waist="Shadow Belt",
    left_ear="Lifestorm Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Solemn Ring",
    right_ring="Persis Ring",
    back={ name="Rosmerta's Cape", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}