sets.exported={
    main={ name="Claidheamh Soluis", augments={'Accuracy+6','"Dbl.Atk."+2','DMG:+9',}},
    sub={ name="Xiutleato", augments={'Occ. atk. twice+8','Crit.hit rate+4',}},
    ammo="Honed Tathlum",
    head={ name="Taeon Chapeau", augments={'Attack+11','Crit.hit rate+3','STR+2',}},
    body="Ayanmo Corazza +1",
    hands="Aya. Manopolas +1",
    legs="Aya. Cosciales +1",
    feet="Aya. Gambieras +1",
    neck="Asperity Necklace",
    waist="Cetl Belt",
    left_ear="Brutal Earring",
    right_ear="Suppanomimi",
    left_ring="Ayanmo Ring",
    right_ring="Mars's Ring",
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+5','Crit.hit rate+10','Damage taken-4%',}},
}