sets.exported={
    main={ name="Claidheamh Soluis", augments={'Accuracy+6','"Dbl.Atk."+2','DMG:+9',}},
    sub={ name="Xiutleato", augments={'Occ. atk. twice+8','Crit.hit rate+4',}},
    ammo="Honed Tathlum",
    head={ name="Iuitl Headgear +1", augments={'Phys. dmg. taken -3%','Magic dmg. taken -2%','"Dbl.Atk."+2',}},
    body={ name="Qaaxo Harness", augments={'Attack+15','Evasion+15','"Dbl.Atk."+2',}},
    hands={ name="Taeon Gloves", augments={'Accuracy+12','"Triple Atk."+2',}},
    legs={ name="Taeon Tights", augments={'Accuracy+11','"Triple Atk."+2',}},
    feet={ name="Taeon Boots", augments={'Accuracy+12','"Triple Atk."+2',}},
    neck="Asperity Necklace",
    waist="Cetl Belt",
    left_ear="Brutal Earring",
    right_ear="Suppanomimi",
    left_ring="Rajas Ring",
    right_ring="Mars's Ring",
    back={ name="Rosmerta's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+5','Crit.hit rate+10','Damage taken-4%',}},
}