sets.exported={
    main={ name="Akademos", augments={'MP+80','INT+20','"Mag.Atk.Bns."+20',}},
    sub="Tokko Grip",
    ammo="Elis Tome",
    head="Jhakri Coronal",
    body="Jhakri Robe",
    hands="Jhakri Cuffs +1",
    legs="Jhakri Slops +1",
    feet="Jhakri Pigaches +1",
    neck="Eddy Necklace",
    waist="Maniacus Sash",
    left_ear="Barkaro. Earring",
    right_ear="Friomisi Earring",
    left_ring="Shiva Ring",
    right_ring="Jhakri Ring",
    back={ name="Bookworm's Cape", augments={'INT+2','MND+2','Helix eff. dur. +19','"Regen" potency+9',}},
}