sets.exported={
    main="Malignance Pole",
    head="C. Palug Crown",
    body="Inyanga Jubbah +1",
    hands="Asteria Mitts +1",
    legs="Assid. Pants +1",
    feet="Inyanga Crackows",
    neck="Loricate Torque +1",
    waist="Channeler's Stone",
    left_ear="Andoaa Earring",
    right_ear="Novia Earring",
    left_ring="Sangoma Ring",
    right_ring="Shneddick Ring",
    back="Scintillating Cape",
}