sets.exported={
    main={ name="Claidheamh Soluis", augments={'Accuracy+6','"Dbl.Atk."+2','DMG:+9',}},
    sub="Arasy Sword",
    ammo="Staunch Tathlum",
    head="Orvail Corona +1",
    body="Chelona Blazer",
    hands="Aya. Manopolas +1",
    legs="Nisse Slacks",
    feet="Chelona Boots",
    neck="Grandiose Chain",
    waist="Qiqirn Sash +1",
    left_ear="Brutal Earring",
    right_ear="Ethereal Earring",
    left_ring="Shneddick Ring",
    right_ring={ name="Dark Ring", augments={'Phys. dmg. taken -3%','Magic dmg. taken -5%',}},
    back="Vita Cape",
}