sets.exported={
    main="Earth Staff",
    sub="Irenic Strap",
    ammo="Staunch Tathlum",
    head="Befouled Crown",
    body="Ebers Bliaud +1",
    hands="Inyanga Dastanas",
    legs="Assid. Pants +1",
    feet={ name="Helios Boots", augments={'"Mag.Atk.Bns."+24','Magic crit. hit rate +6','MP+9',}},
    neck="Twilight Torque",
    waist="Fucho-no-Obi",
    left_ear="Lifestorm Earring",
    right_ear="Novia Earring",
    left_ring="Defending Ring",
    right_ring="Shneddick Ring",
    back="Cheviot Cape",
}