sets.exported={
    main="Iridal Staff",
    sub="Amicus Grip",
    ammo="Clarus Stone",
    head={ name="Gende. Caubeen", augments={'Phys. dmg. taken -2%','"Cure" potency +2%',}},
    body="Theo. Briault",
    hands={ name="Bokwus Gloves", augments={'Mag. Acc.+6','MND+1',}},
    legs="Ebers Pantaloons",
    feet={ name="Vanya Clogs", augments={'MP+50','"Cure" potency +7%','Enmity-6',}},
    neck="Cleric's Torque",
    waist="Pythia Sash",
    left_ear="Lifestorm Earring",
    right_ear="Novia Earring",
    left_ring="Mediator's Ring",
    right_ring="Ephedra Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','MND+5','Enmity-10','Damage taken-5%',}},
}