sets.exported={
    main="Tupsimati",
    head="Scholar's M.board",
    body="Scholar's Gown",
    hands={ name="Teal Cuffs", augments={'Haste+2','INT+4','System: 1 ID: 131 Val: 5',}},
    legs="Scholar's Pants",
    feet="Scholar's Loafers",
    neck={ name="Enlightened Chain", augments={'Haste+2','System: 1 ID: 131 Val: 1','INT+4',}},
    waist={ name="Penitent's Rope", augments={'Haste+2','System: 1 ID: 131 Val: 1','INT+4',}},
    left_ear={ name="Phantom Earring", augments={'Haste+2','System: 1 ID: 131 Val: 1','INT+4',}},
    right_ear={ name="Phantom Earring", augments={'Haste+2','System: 1 ID: 131 Val: 1','INT+4',}},
    left_ring={ name="Diamond Ring", augments={'Haste+2','System: 1 ID: 131 Val: 1','INT+4',}},
    right_ring={ name="Diamond Ring", augments={'Haste+2','System: 1 ID: 131 Val: 1','INT+4',}},
    back="Cheviot Cape",
}