
	organizer_items = {
		echos="Echo Drops",
		remedy="Remedy",
		warpring="Warp ring",
		trizek="Trizek Ring",
		prism="Prism powder",
		silent="Silent oil",
		echad="Echad Ring",
		capacity="Capacity Ring",
		expertise="Expertise Ring",
		demring="Dimensional ring (Dem)",
		holring="Dimensional ring (Holla)",
		mearing="Dimensional ring (Mea)",
		wcudgel="Warp cudgel",
		facring="Facility ring",
		reraisehairpin="Reraise Hairpin",
		clothbody="Weaver's apron",
		endring="Endorsement Ring",
		emporring="Emporox's Ring",
		talaria="Talaria",
		vile="Vile elixir",
		vile1="Vile elixir +1",
		hielixir="Hi-Elixir",
		proether="Pro-Ether",
		instreraise="Instant reraise",
		instwarp="Instant warp",
		synergygloves="Carpenter's Cuffs",
		craftkeeper="Craftkeeper's ring",
		craftmaster="Craftmaster's ring",
		artificers="Artificer's ring",
		clothcraftshield="Plaiter's Shield",
		
	}
